services:

  db:
    image: mysql:8.0
    container_name: romanico-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=romanico
      - MYSQL_USER=romanico
      - MYSQL_PASSWORD=romanico123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: romanico-backend
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9003:9000"

  backend-nginx:
    image: nginx:alpine
    container_name: romanico-backend-nginx
    depends_on:
      - backend
    ports:
      - "8083:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_data:
