services:

  db:
    image: mysql:8.0
    container_name: romanico-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: romanico
      MYSQL_USER: romanico
      MYSQL_PASSWORD: romanico123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - romanico-net
    # IMPORTANTE: sin "ports: 3306:3306"
    # La base de datos queda totalmente aislada


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: romanico-backend
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html
    networks:
      - romanico-net
    # NO exponer 9000 hacia fuera
    # NGINX se encargar√° de servir la app


  backend-nginx:
    image: nginx:alpine
    container_name: romanico-backend-nginx
    depends_on:
      - backend
    ports:
      - "8083:80"   # Solo NGINX se expone hacia la LAN
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - romanico-net   # Puede acceder al backend


volumes:
  db_data:

networks:
  romanico-net:
    driver: bridge
